#!/bin/bash
# makes sure the folder containing the script will be the root folder
cd "$(dirname "$0")" || exit

# Colors for printing messages
NC='\033[0m' # No Color
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'

print_info() {
  echo -e "${GREEN} [ info ] ${NC}" "$1"
}

print_info "📦  Package $FORMATTED_NAME"

# Get the URL of the origin remote
remote_url=$(git config --get remote.origin.url)

# Extract the repository name from the URL
REPOSITORY_NAME=$(basename -s .git "$remote_url")

# Output the repository name
print_info "Repository Name: $REPOSITORY_NAME"

## prepare the package folder
mkdir -p ../../../package/$REPOSITORY_NAME

# copy the files to the package folder
cp -rfv ../out/* ../../../package/$REPOSITORY_NAME

# cp -rfv ../public/* ../../../package/$REPOSITORY_NAME

## create a .nojekyll file
## needed for github pages
# touch ../../../package/$REPOSITORY_NAME/.nojekyll
# echo -e "$GREEN [ info ] $NC .nojekyll created and added. $NC"

## create a CNAME file
## needed for github pages
# echo "Create a CNAME file"
# touch ../../../package/$REPOSITORY_NAME/CNAME
# echo $DOMAIN > ../../../package/$REPOSITORY_NAME/CNAME
