import Head from "next/head";
import BlogCategoryTemplate from "@/core/templates/BlogCategory.template.js";
import getContent from "@/core/utils/content/getContent";

export default function BlogCategory({ children, pageContent, siteProps }) {
    return (
        <div>
            <Head>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href={siteProps.icons.favicon} />
            </Head>
            <BlogCategoryTemplate pageContent={pageContent} siteProps={siteProps}>
                {children}
            </BlogCategoryTemplate>
        </div>
    );
}

export async function getStaticProps() {
    const publishedPosts = getContent().posts.filter(
        (post) => post.frontmatter.status === "published"
    );
    return {
        props: {
            pageContent: {
                heroBanner: {
                    pageTitle: "Blog posts",
                    subheading: "Thoughts and insights on Web Development.",
                },
                main: {
                    title: "Posts",
                    section_id: "posts",
                    children: {
                        postsOverview: {
                            list: publishedPosts.slice(0, 12),
                            parentPage: "blog",
                            category: {
                                category_url: "post",
                                category_name: "post",
                            },
                        },
                    },
                },
            },
        },
    };
}
