import Head from 'next/head';
import PortfolioCategoryTemplate from '@/core/templates/PortfolioCategory.template.js';
import getContent from '@/core/utils/content/getContent';
import { Roboto } from 'next/font/google';
import filterByFrontmatter from '@/core/utils/filterByFrontMatter';
const roboto = Roboto({
  display: 'swap',
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  style: ['normal'],
  variable: '--text-regular',
});

export default function PortfolioCategoryPage({ children, pageContent, siteProps }) {
  const pageTitle = ['Case Studies', '|', siteProps.title].join(' ');

  return (
    <div className={roboto.className}>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={siteProps.icons.favicon} />
      </Head>
      <PortfolioCategoryTemplate siteProps={siteProps} pageContent={pageContent}></PortfolioCategoryTemplate>
    </div>
  );
}

export async function getStaticProps() {
  const publishedCoursework = await getContent().then((fetchedContent) => {
    const { content } = fetchedContent;
    return filterByFrontmatter(content.courseworks, ['status'], { status: 'published' });
  });
  return {
    props: {
      pageContent: {
        main: {
          heroBanner: {
            pageTitle: 'Coursework Gallery',
            subheading:
              'Academic or educational projects assigned as part of a course or program that demonstrate my ability to apply knowledge and techniques.',
          },
          section: {
            section_id: 'coursework_overview',
            children: {
              portfolioOverview: {
                projects: publishedCoursework,
                parentPage: 'category_page',
                category: {
                  category_url: 'courseworks',
                  category_name: 'courseworks',
                },
              },
            },
          },
        },
      },
    },
  };
}
