name: Deploy Portfolio Website to Github Pages
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Portfolio Website
    runs-on: ubuntu-latest
    steps:
      - name: "📥 checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "🔄  Cache node_modules"
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: "🔧 Setup NodeJS 14.19.1"
        uses: actions/setup-node@v1
        with:
          node-version: 14.19.1

      - name: "🔧 Install npm@latest"
        run: npm i -g npm@latest

      - name: "📦  Install Assets dependencies"
        run: |
          bash scripts/assets-install.bash

      - name: "📦  Install Portfolio Website Development dependencies"
        run: |
          bash scripts/frontend-portfolio-website-install.bash

      - name: "🏗️  Build Frontend Portfolio Website"
        run: |
          bash scripts/assets-process.bash
          bash scripts/frontend-portfolio-website-build.bash production

      - name: "🚚  Package Portfolio Website"
        run: |
          bash scripts/package-clean.bash
          bash scripts/package-portfolio-website.bash

      - name: "🚀 Deploy to GitHub Pages"
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages-portfolio-website
          folder: package/portfolio-website

