---
version: "3.7"
services:

  # ---------------------------------------------------------------------
  # | Nginx-Service                                                     |
  # ---------------------------------------------------------------------
  nginx:
    build:
      context: ../backend/portfolio-website
      dockerfile: portfolio-website.Dockerfile
    container_name: portfolio-website
    restart: unless-stopped
    volumes:
      - ../frontend/portfolio-website/dist:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.portfolio-website.entrypoints=web
      - traefik.http.routers.portfolio-website.middlewares=test-redirectscheme
      - traefik.http.routers.portfolio-website-secure.entrypoints=websecure
      - traefik.http.routers.portfolio-website-secure.tls.certresolver=myresolver
      - traefik.http.routers.portfolio-website-secure.tls=true
      - traefik.http.routers.portfolio-website-secure.middlewares=test-compress,test-redirectscheme
      # Services
      - traefik.http.services.portfolio-website-secure.loadbalancer.server.port=80
      # Middlewares
      - traefik.http.middlewares.test-compress.compress=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.port=443
