import Head from "next/head";
import Generic from "@/core/templates/Generic/Generic.template.js";

export default function Elements() {
    return (
        <div>
            <Head>
                <title>Elements | Paul Serban: JS Software Engineer</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Generic></Generic>
        </div>
    );
}
