import Head from "next/head";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Paul Serban | JS Software Engineer</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <header>
                    <h1>Header</h1>
                </header>
                <main>
                    <h2>Main</h2>
                </main>
                <footer>
                    <p>footer</p>
                </footer>
            </main>
        </div>
    );
}
