import Head from "next/head";
import GenericTemplate from "@/core/templates/Generic/Generic.template.js";
import Section from "@/core/library/organisms/Section.organism";
import Main from "@/core/library/organisms/Main.organism";
import HeroBanner from "@/core/library/organisms/HeroBanner.organism";

const siteNavLinks = [
    { label: "portfolio", href: `/portfolio` },
    { label: "blog", href: `/blog` },
    { label: "cv", href: `/cv` },
];

const pageNavLinks = [
    { label: "posts", href: "#posts" },
    { label: "Snippets", href: "#snippets" },
    { label: "booknotes", href: "#booknotes" }
];

const socialMediaList = [
    { label: "Twitter", href: "http://twitter.com"},
    { label: "Instagram", href: "http://instagram.com"},
    { label: "Medium", href: "http://medium.com"},
    { label: "Mastodon", href: "http://mastodon.com"},
];

export default function Blog() {
    return (
        <div>
            <Head>
                <title>Paul Serban | Blog | Software Engineer</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <GenericTemplate
                siteNavLinks={siteNavLinks}
                pageNavLinks={pageNavLinks}
            >
                <HeroBanner
                    pageTitle="Lets Be Inquisitive:"
                    subheading="Dive into my web development blog and checkout my insightful shares."
                    socialMediaList={socialMediaList}
                />
                <Main>
                    <Section headingTitle="Posts" sectionId="posts"></Section>
                    <Section headingTitle="Snippets" sectionId="snippets"></Section>
                    <Section headingTitle="Booknotes" sectionId="booknotes"></Section>
                </Main>
            </GenericTemplate>
        </div>
    );
}
