// import Head from "next/head";
// import BlogPostTemplate from "@/core/templates/BlogPost.template.js";

// export default function BlogPost({ children, pageContent, siteProps }) {
//     return (
//         <div>
//             <Head>
//                 <title>Paul Serban | Blog | Software Engineer</title>
//                 <meta
//                     name="description"
//                     content="Generated by create next app"
//                 />
//                 <meta
//                     name="viewport"
//                     content="width=device-width, initial-scale=1"
//                 />
//                 <link rel="icon" href={siteProps.icons.favicon} />
//             </Head>
//             <BlogPostTemplate siteNavLinks={siteProps.siteNavLinks}>
//                 {children}
//             </BlogPostTemplate>
//         </div>
//     );
// }
