import Head from "next/head";

import GenericTemplate from "@/core/templates/Generic/Generic.template.js";
import Section from "@/core/library/organisms/Section.organism";
import Main from "@/core/library/organisms/Main.organism";
import HeroBanner from "@/core/library/organisms/HeroBanner.organism";
import ProjectGallery from "@/core/library/organisms/ProjectGallery.organism";

import getPortfolio from "@/utils/content/getPortfolio";

const siteNavLinks = [
    { label: "portfolio", href: `/portfolio` },
    { label: "blog", href: `/blog` },
    // { label: "cv", href: `/cv` },
];

const pageNavLinks = [
    { label: "projects", href: "#projects" },
    { label: "coursework", href: "#coursework" },
];

const socialMediaList = [
    { label: "Github", icon: "github", href: "https://github.com" },
    { label: "CodePen", icon: "codepen", href: "https://codepen.io" },
    {
        label: "HackerRank",
        icon: "hackerrank",
        href: "https://www.hackerrank.com",
    },
    { label: "CodeWars", icon: "codewars", href: "https://codewars.com" },
    { label: "HackTheBox", icon: "hackthebox", href: "https://hackthebox.com" },
    { label: "TryHackMe", icon: "tryhackme", href: "https://tryhackme.com" },
];

export default function Portfolio({
    projectList = [],
    courseWorkList = [],
    caseStudiesList,
}) {
    return (
        <div>
            <Head>
                <title>Paul Serban | Portfolio | Software Engineer</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <GenericTemplate
                siteNavLinks={siteNavLinks}
                pageNavLinks={pageNavLinks}
            >
                <HeroBanner
                    pageTitle="Explore My Expertise:"
                    subheading="A gallery of Web Development Projects and Coursework"
                    socialMediaList={socialMediaList}
                />
                <Main>
                    <Section
                        headingTitle="Projects"
                        sectionId="projects"
                        subheadingText="Projects undertaken for personal or hobby purposes that showcase my skills and creativity."
                    >
                        {/* gallery of projects filtered by tag in the url query */}
                        <ProjectGallery projectList={projectList} />
                    </Section>
                    <Section
                        headingTitle="Case Studies"
                        sectionId="case_studies"
                        subheadingText="Projects that involve research, analysis, and problem-solving, in which you have applied 
                        my skills and knowledge to real-world scenarios. These projects showcase my ability to tackle complex 
                        challenges and provide solutions."
                    >
                        {/* gallery of case studies filtered by tag in the url query */}
                        <ProjectGallery projectList={caseStudiesList} />
                    </Section>
                    <Section
                        headingTitle="Coursework"
                        sectionId="coursework"
                        subheadingText="Academic or educational projects assigned as part of a course or program that demonstrate my ability to apply knowledge and techniques."
                    >
                        {/* gallery of coursework filtered by tag in the url query */}
                        <ProjectGallery projectList={courseWorkList} />
                    </Section>
                </Main>
            </GenericTemplate>
        </div>
    );
}

export async function getStaticProps({}) {
    return {
        props: {
            projectList: getPortfolio().projects.published,
            courseWorkList: getPortfolio().courseWork.published,
            caseStudiesList: getPortfolio().caseStudies.published,
        },
    };
}
