import Head from "next/head";

import GenericTemplate from "@/core/templates/Generic/Generic.template.js";
import Section from "@/core/library/organisms/Section.organism";
import Main from "@/core/library/organisms/Main.organism";
import HeroBanner from "@/core/library/organisms/HeroBanner.organism";

const siteNavLinks = [
    { label: "portfolio", href: `/portfolio` },
    { label: "blog", href: `/blog` },
    { label: "cv", href: `/cv` },
];

const pageNavLinks = [
    { label: "projects", href: "#projects" },
    { label: "coursework", href: "#coursework" },
];

const socialMediaList = [
    { label: "Github", icon: "github", href: "https://github.com" },
    { label: "CodePen", icon: "codepen", href: "https://codepen.io" },
    {
        label: "HackerRank",
        icon: "hackerrank",
        href: "https://www.hackerrank.com",
    },
    { label: "CodeWars", icon: "codewars", href: "https://codewars.com" },
    { label: "HackTheBox", icon: "hackthebox", href: "https://hackthebox.com" },
    { label: "TryHackMe", icon: "tryhackme", href: "https://tryhackme.com" },
];

export default function Portfolio() {
    return (
        <div>
            <Head>
                <title>Paul Serban | Portfolio | Software Engineer</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <GenericTemplate
                siteNavLinks={siteNavLinks}
                pageNavLinks={pageNavLinks}
            >
                <HeroBanner
                    pageTitle="Explore My Expertise:"
                    subheading="A gallery of Web Development Projects and Coursework"
                    socialMediaList={socialMediaList}
                />
                <Main>
                    <Section
                        headingTitle="Projects"
                        sectionId="projects"
                    ></Section>
                    <Section
                        headingTitle="Coursework"
                        sectionId="coursework"
                    ></Section>
                </Main>
            </GenericTemplate>
        </div>
    );
}
